// This file is @generated by prost-build.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct VersionRequest {
    #[prost(string, tag = "1")]
    pub version: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct VersionResponse {
    #[prost(string, tag = "1")]
    pub version: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub runtime_name: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub runtime_version: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub runtime_api_version: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PodSandboxMetadata {
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub uid: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub namespace: ::prost::alloc::string::String,
    #[prost(uint32, tag = "4")]
    pub attempt: u32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct LinuxPodSandboxConfig {
    #[prost(string, tag = "1")]
    pub cgroup_parent: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "2")]
    pub security_context: ::core::option::Option<LinuxSandboxSecurityContext>,
    #[prost(map = "string, string", tag = "3")]
    pub sysctls:
        ::std::collections::HashMap<::prost::alloc::string::String, ::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct LinuxSandboxSecurityContext {
    #[prost(message, optional, tag = "1")]
    pub namespace_options: ::core::option::Option<NamespaceOption>,
    #[prost(message, optional, tag = "2")]
    pub selinux_options: ::core::option::Option<SeLinuxOption>,
    #[prost(message, optional, tag = "3")]
    pub run_as_user: ::core::option::Option<Int64Value>,
    #[prost(bool, tag = "4")]
    pub readonly_rootfs: bool,
    #[prost(int64, repeated, tag = "5")]
    pub supplemental_groups: ::prost::alloc::vec::Vec<i64>,
    #[prost(bool, tag = "6")]
    pub privileged: bool,
    /// deprecated
    #[prost(string, tag = "7")]
    pub seccomp_profile_path: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "8")]
    pub run_as_group: ::core::option::Option<Int64Value>,
    #[prost(message, optional, tag = "9")]
    pub seccomp: ::core::option::Option<SecurityProfile>,
    #[prost(message, optional, tag = "10")]
    pub apparmor: ::core::option::Option<SecurityProfile>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct NamespaceOption {
    #[prost(enumeration = "NamespaceMode", tag = "1")]
    pub network: i32,
    #[prost(enumeration = "NamespaceMode", tag = "2")]
    pub pid: i32,
    #[prost(enumeration = "NamespaceMode", tag = "3")]
    pub ipc: i32,
    #[prost(string, tag = "4")]
    pub target_id: ::prost::alloc::string::String,
    #[prost(enumeration = "NamespaceMode", tag = "5")]
    pub userns: i32,
    #[prost(enumeration = "NamespaceMode", tag = "6")]
    pub uts: i32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SeLinuxOption {
    #[prost(string, tag = "1")]
    pub user: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub role: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub r#type: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub level: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct Int64Value {
    #[prost(int64, tag = "1")]
    pub value: i64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SecurityProfile {
    #[prost(enumeration = "SecurityProfileType", tag = "1")]
    pub profile_type: i32,
    #[prost(string, tag = "2")]
    pub localhost_ref: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Capability {
    #[prost(string, repeated, tag = "1")]
    pub add_capabilities: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(string, repeated, tag = "2")]
    pub drop_capabilities: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DnsConfig {
    #[prost(string, repeated, tag = "1")]
    pub servers: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(string, repeated, tag = "2")]
    pub searches: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(string, repeated, tag = "3")]
    pub options: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PortMapping {
    #[prost(enumeration = "Protocol", tag = "1")]
    pub protocol: i32,
    #[prost(int32, tag = "2")]
    pub container_port: i32,
    #[prost(int32, tag = "3")]
    pub host_port: i32,
    #[prost(string, tag = "4")]
    pub host_ip: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Mount {
    #[prost(string, tag = "1")]
    pub container_path: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub host_path: ::prost::alloc::string::String,
    #[prost(bool, tag = "3")]
    pub readonly: bool,
    #[prost(bool, tag = "4")]
    pub selinux_relabel: bool,
    #[prost(enumeration = "MountPropagation", tag = "5")]
    pub propagation: i32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PodSandboxConfig {
    #[prost(message, optional, tag = "1")]
    pub metadata: ::core::option::Option<PodSandboxMetadata>,
    #[prost(string, tag = "2")]
    pub hostname: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub log_directory: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "4")]
    pub dns_config: ::core::option::Option<DnsConfig>,
    #[prost(message, repeated, tag = "5")]
    pub port_mappings: ::prost::alloc::vec::Vec<PortMapping>,
    #[prost(map = "string, string", tag = "6")]
    pub labels:
        ::std::collections::HashMap<::prost::alloc::string::String, ::prost::alloc::string::String>,
    #[prost(map = "string, string", tag = "7")]
    pub annotations:
        ::std::collections::HashMap<::prost::alloc::string::String, ::prost::alloc::string::String>,
    #[prost(message, optional, tag = "8")]
    pub linux: ::core::option::Option<LinuxPodSandboxConfig>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RunPodSandboxRequest {
    #[prost(message, optional, tag = "1")]
    pub config: ::core::option::Option<PodSandboxConfig>,
    #[prost(string, tag = "2")]
    pub runtime_handler: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RunPodSandboxResponse {
    #[prost(string, tag = "1")]
    pub pod_sandbox_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct StopPodSandboxRequest {
    #[prost(string, tag = "1")]
    pub pod_sandbox_id: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct StopPodSandboxResponse {}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RemovePodSandboxRequest {
    #[prost(string, tag = "1")]
    pub pod_sandbox_id: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct RemovePodSandboxResponse {}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PodSandboxStatusRequest {
    #[prost(string, tag = "1")]
    pub pod_sandbox_id: ::prost::alloc::string::String,
    #[prost(bool, tag = "2")]
    pub verbose: bool,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PodSandboxStatusResponse {
    #[prost(message, optional, tag = "1")]
    pub status: ::core::option::Option<PodSandboxStatus>,
    #[prost(map = "string, string", tag = "2")]
    pub info:
        ::std::collections::HashMap<::prost::alloc::string::String, ::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PodSandboxStatus {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "2")]
    pub metadata: ::core::option::Option<PodSandboxMetadata>,
    #[prost(enumeration = "PodSandboxState", tag = "3")]
    pub state: i32,
    #[prost(int64, tag = "4")]
    pub created_at: i64,
    #[prost(message, optional, tag = "5")]
    pub network: ::core::option::Option<PodSandboxNetworkStatus>,
    #[prost(map = "string, string", tag = "6")]
    pub labels:
        ::std::collections::HashMap<::prost::alloc::string::String, ::prost::alloc::string::String>,
    #[prost(map = "string, string", tag = "7")]
    pub annotations:
        ::std::collections::HashMap<::prost::alloc::string::String, ::prost::alloc::string::String>,
    #[prost(string, tag = "8")]
    pub runtime_handler: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PodSandboxNetworkStatus {
    #[prost(string, tag = "1")]
    pub ip: ::prost::alloc::string::String,
    #[prost(message, repeated, tag = "2")]
    pub additional_ips: ::prost::alloc::vec::Vec<PodIp>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PodIp {
    #[prost(string, tag = "1")]
    pub ip: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListPodSandboxRequest {
    #[prost(message, optional, tag = "1")]
    pub filter: ::core::option::Option<PodSandboxFilter>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListPodSandboxResponse {
    #[prost(message, repeated, tag = "1")]
    pub items: ::prost::alloc::vec::Vec<PodSandbox>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PodSandboxFilter {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(enumeration = "PodSandboxState", tag = "2")]
    pub state: i32,
    #[prost(map = "string, string", tag = "3")]
    pub label_selector:
        ::std::collections::HashMap<::prost::alloc::string::String, ::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PodSandbox {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "2")]
    pub metadata: ::core::option::Option<PodSandboxMetadata>,
    #[prost(enumeration = "PodSandboxState", tag = "3")]
    pub state: i32,
    #[prost(int64, tag = "4")]
    pub created_at: i64,
    #[prost(map = "string, string", tag = "5")]
    pub labels:
        ::std::collections::HashMap<::prost::alloc::string::String, ::prost::alloc::string::String>,
    #[prost(map = "string, string", tag = "6")]
    pub annotations:
        ::std::collections::HashMap<::prost::alloc::string::String, ::prost::alloc::string::String>,
    #[prost(string, tag = "7")]
    pub runtime_handler: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ContainerMetadata {
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    #[prost(uint32, tag = "2")]
    pub attempt: u32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ImageSpec {
    #[prost(string, tag = "1")]
    pub image: ::prost::alloc::string::String,
    #[prost(map = "string, string", tag = "2")]
    pub annotations:
        ::std::collections::HashMap<::prost::alloc::string::String, ::prost::alloc::string::String>,
    #[prost(string, tag = "18")]
    pub user_specified_image: ::prost::alloc::string::String,
    #[prost(string, tag = "19")]
    pub runtime_handler: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct KeyValue {
    #[prost(string, tag = "1")]
    pub key: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub value: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct LinuxContainerResources {
    #[prost(int64, tag = "1")]
    pub cpu_period: i64,
    #[prost(int64, tag = "2")]
    pub cpu_quota: i64,
    #[prost(int64, tag = "3")]
    pub cpu_shares: i64,
    #[prost(int64, tag = "4")]
    pub memory_limit_bytes: i64,
    #[prost(int64, tag = "5")]
    pub oom_score_adj: i64,
    #[prost(string, tag = "6")]
    pub cpuset_cpus: ::prost::alloc::string::String,
    #[prost(string, tag = "7")]
    pub cpuset_mems: ::prost::alloc::string::String,
    #[prost(int64, tag = "8")]
    pub memory_swap_limit_bytes: i64,
    #[prost(message, repeated, tag = "9")]
    pub hugepage_limits: ::prost::alloc::vec::Vec<HugepageLimit>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct HugepageLimit {
    #[prost(string, tag = "1")]
    pub page_size: ::prost::alloc::string::String,
    #[prost(uint64, tag = "2")]
    pub limit: u64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct LinuxContainerSecurityContext {
    #[prost(message, optional, tag = "1")]
    pub capabilities: ::core::option::Option<Capability>,
    #[prost(bool, tag = "2")]
    pub privileged: bool,
    #[prost(message, optional, tag = "3")]
    pub namespace_options: ::core::option::Option<NamespaceOption>,
    #[prost(message, optional, tag = "4")]
    pub selinux_options: ::core::option::Option<SeLinuxOption>,
    #[prost(message, optional, tag = "5")]
    pub run_as_user: ::core::option::Option<Int64Value>,
    #[prost(string, tag = "6")]
    pub run_as_username: ::prost::alloc::string::String,
    #[prost(bool, tag = "7")]
    pub readonly_rootfs: bool,
    #[prost(int64, repeated, tag = "8")]
    pub supplemental_groups: ::prost::alloc::vec::Vec<i64>,
    /// deprecated
    #[prost(string, tag = "9")]
    pub apparmor_profile: ::prost::alloc::string::String,
    /// deprecated
    #[prost(string, tag = "10")]
    pub seccomp_profile_path: ::prost::alloc::string::String,
    #[prost(bool, tag = "11")]
    pub no_new_privs: bool,
    #[prost(message, optional, tag = "12")]
    pub run_as_group: ::core::option::Option<Int64Value>,
    #[prost(string, repeated, tag = "13")]
    pub masked_paths: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(string, repeated, tag = "14")]
    pub readonly_paths: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(message, optional, tag = "15")]
    pub seccomp: ::core::option::Option<SecurityProfile>,
    #[prost(message, optional, tag = "16")]
    pub apparmor: ::core::option::Option<SecurityProfile>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct LinuxContainerConfig {
    #[prost(message, optional, tag = "1")]
    pub resources: ::core::option::Option<LinuxContainerResources>,
    #[prost(message, optional, tag = "2")]
    pub security_context: ::core::option::Option<LinuxContainerSecurityContext>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ContainerConfig {
    #[prost(message, optional, tag = "1")]
    pub metadata: ::core::option::Option<ContainerMetadata>,
    #[prost(message, optional, tag = "2")]
    pub image: ::core::option::Option<ImageSpec>,
    #[prost(string, repeated, tag = "3")]
    pub command: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(string, repeated, tag = "4")]
    pub args: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(string, tag = "5")]
    pub working_dir: ::prost::alloc::string::String,
    #[prost(message, repeated, tag = "6")]
    pub envs: ::prost::alloc::vec::Vec<KeyValue>,
    #[prost(message, repeated, tag = "7")]
    pub mounts: ::prost::alloc::vec::Vec<Mount>,
    #[prost(message, repeated, tag = "8")]
    pub devices: ::prost::alloc::vec::Vec<Device>,
    #[prost(map = "string, string", tag = "9")]
    pub labels:
        ::std::collections::HashMap<::prost::alloc::string::String, ::prost::alloc::string::String>,
    #[prost(map = "string, string", tag = "10")]
    pub annotations:
        ::std::collections::HashMap<::prost::alloc::string::String, ::prost::alloc::string::String>,
    #[prost(string, tag = "11")]
    pub log_path: ::prost::alloc::string::String,
    #[prost(bool, tag = "12")]
    pub stdin: bool,
    #[prost(bool, tag = "13")]
    pub stdin_once: bool,
    #[prost(bool, tag = "14")]
    pub tty: bool,
    #[prost(message, optional, tag = "15")]
    pub linux: ::core::option::Option<LinuxContainerConfig>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Device {
    #[prost(string, tag = "1")]
    pub container_path: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub host_path: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub permissions: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CreateContainerRequest {
    #[prost(string, tag = "1")]
    pub pod_sandbox_id: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "2")]
    pub config: ::core::option::Option<ContainerConfig>,
    #[prost(message, optional, tag = "3")]
    pub sandbox_config: ::core::option::Option<PodSandboxConfig>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CreateContainerResponse {
    #[prost(string, tag = "1")]
    pub container_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct StartContainerRequest {
    #[prost(string, tag = "1")]
    pub container_id: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct StartContainerResponse {}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct StopContainerRequest {
    #[prost(string, tag = "1")]
    pub container_id: ::prost::alloc::string::String,
    #[prost(int64, tag = "2")]
    pub timeout: i64,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct StopContainerResponse {}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RemoveContainerRequest {
    #[prost(string, tag = "1")]
    pub container_id: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct RemoveContainerResponse {}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListContainersRequest {
    #[prost(message, optional, tag = "1")]
    pub filter: ::core::option::Option<ContainerFilter>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListContainersResponse {
    #[prost(message, repeated, tag = "1")]
    pub containers: ::prost::alloc::vec::Vec<Container>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ContainerFilter {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(enumeration = "ContainerState", tag = "2")]
    pub state: i32,
    #[prost(string, tag = "3")]
    pub pod_sandbox_id: ::prost::alloc::string::String,
    #[prost(map = "string, string", tag = "4")]
    pub label_selector:
        ::std::collections::HashMap<::prost::alloc::string::String, ::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Container {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub pod_sandbox_id: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "3")]
    pub metadata: ::core::option::Option<ContainerMetadata>,
    #[prost(message, optional, tag = "4")]
    pub image: ::core::option::Option<ImageSpec>,
    #[prost(string, tag = "5")]
    pub image_ref: ::prost::alloc::string::String,
    #[prost(enumeration = "ContainerState", tag = "6")]
    pub state: i32,
    #[prost(int64, tag = "7")]
    pub created_at: i64,
    #[prost(map = "string, string", tag = "8")]
    pub labels:
        ::std::collections::HashMap<::prost::alloc::string::String, ::prost::alloc::string::String>,
    #[prost(map = "string, string", tag = "9")]
    pub annotations:
        ::std::collections::HashMap<::prost::alloc::string::String, ::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ContainerStatusRequest {
    #[prost(string, tag = "1")]
    pub container_id: ::prost::alloc::string::String,
    #[prost(bool, tag = "2")]
    pub verbose: bool,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ContainerStatusResponse {
    #[prost(message, optional, tag = "1")]
    pub status: ::core::option::Option<ContainerStatus>,
    #[prost(map = "string, string", tag = "2")]
    pub info:
        ::std::collections::HashMap<::prost::alloc::string::String, ::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ContainerStatus {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "2")]
    pub metadata: ::core::option::Option<ContainerMetadata>,
    #[prost(enumeration = "ContainerState", tag = "3")]
    pub state: i32,
    #[prost(int64, tag = "4")]
    pub created_at: i64,
    #[prost(int64, tag = "5")]
    pub started_at: i64,
    #[prost(int64, tag = "6")]
    pub finished_at: i64,
    #[prost(int32, tag = "7")]
    pub exit_code: i32,
    #[prost(message, optional, tag = "8")]
    pub image: ::core::option::Option<ImageSpec>,
    #[prost(string, tag = "9")]
    pub image_ref: ::prost::alloc::string::String,
    #[prost(string, tag = "10")]
    pub reason: ::prost::alloc::string::String,
    #[prost(string, tag = "11")]
    pub message: ::prost::alloc::string::String,
    #[prost(map = "string, string", tag = "12")]
    pub labels:
        ::std::collections::HashMap<::prost::alloc::string::String, ::prost::alloc::string::String>,
    #[prost(map = "string, string", tag = "13")]
    pub annotations:
        ::std::collections::HashMap<::prost::alloc::string::String, ::prost::alloc::string::String>,
    #[prost(message, repeated, tag = "14")]
    pub mounts: ::prost::alloc::vec::Vec<Mount>,
    #[prost(string, tag = "15")]
    pub log_path: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ContainerStatsRequest {
    #[prost(string, tag = "1")]
    pub container_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ContainerStatsResponse {
    #[prost(message, optional, tag = "1")]
    pub stats: ::core::option::Option<ContainerStats>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ContainerStats {
    #[prost(message, optional, tag = "1")]
    pub attributes: ::core::option::Option<ContainerAttributes>,
    #[prost(message, optional, tag = "2")]
    pub cpu: ::core::option::Option<CpuUsage>,
    #[prost(message, optional, tag = "3")]
    pub memory: ::core::option::Option<MemoryUsage>,
    #[prost(message, optional, tag = "4")]
    pub writable_layer: ::core::option::Option<FilesystemUsage>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ContainerAttributes {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "2")]
    pub metadata: ::core::option::Option<ContainerMetadata>,
    #[prost(map = "string, string", tag = "3")]
    pub labels:
        ::std::collections::HashMap<::prost::alloc::string::String, ::prost::alloc::string::String>,
    #[prost(map = "string, string", tag = "4")]
    pub annotations:
        ::std::collections::HashMap<::prost::alloc::string::String, ::prost::alloc::string::String>,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct CpuUsage {
    #[prost(int64, tag = "1")]
    pub timestamp: i64,
    #[prost(message, optional, tag = "2")]
    pub usage_core_nano_seconds: ::core::option::Option<UInt64Value>,
    #[prost(message, optional, tag = "3")]
    pub usage_nano_cores: ::core::option::Option<UInt64Value>,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct MemoryUsage {
    #[prost(int64, tag = "1")]
    pub timestamp: i64,
    #[prost(message, optional, tag = "2")]
    pub working_set_bytes: ::core::option::Option<UInt64Value>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FilesystemUsage {
    #[prost(int64, tag = "1")]
    pub timestamp: i64,
    #[prost(message, optional, tag = "2")]
    pub fs_id: ::core::option::Option<FilesystemIdentifier>,
    #[prost(message, optional, tag = "3")]
    pub used_bytes: ::core::option::Option<UInt64Value>,
    #[prost(message, optional, tag = "4")]
    pub inodes_used: ::core::option::Option<UInt64Value>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FilesystemIdentifier {
    #[prost(string, tag = "1")]
    pub mountpoint: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct UInt64Value {
    #[prost(uint64, tag = "1")]
    pub value: u64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ExecSyncRequest {
    #[prost(string, tag = "1")]
    pub container_id: ::prost::alloc::string::String,
    #[prost(string, repeated, tag = "2")]
    pub cmd: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(int64, tag = "3")]
    pub timeout: i64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ExecSyncResponse {
    #[prost(bytes = "vec", tag = "1")]
    pub stdout: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", tag = "2")]
    pub stderr: ::prost::alloc::vec::Vec<u8>,
    #[prost(int32, tag = "3")]
    pub exit_code: i32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ExecRequest {
    #[prost(string, tag = "1")]
    pub container_id: ::prost::alloc::string::String,
    #[prost(string, repeated, tag = "2")]
    pub cmd: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(bool, tag = "3")]
    pub tty: bool,
    #[prost(bool, tag = "4")]
    pub stdin: bool,
    #[prost(bool, tag = "5")]
    pub stdout: bool,
    #[prost(bool, tag = "6")]
    pub stderr: bool,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ExecResponse {
    #[prost(string, tag = "1")]
    pub url: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AttachRequest {
    #[prost(string, tag = "1")]
    pub container_id: ::prost::alloc::string::String,
    #[prost(bool, tag = "2")]
    pub stdin: bool,
    #[prost(bool, tag = "3")]
    pub tty: bool,
    #[prost(bool, tag = "4")]
    pub stdout: bool,
    #[prost(bool, tag = "5")]
    pub stderr: bool,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AttachResponse {
    #[prost(string, tag = "1")]
    pub url: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PortForwardRequest {
    #[prost(string, tag = "1")]
    pub pod_sandbox_id: ::prost::alloc::string::String,
    #[prost(int32, repeated, tag = "2")]
    pub port: ::prost::alloc::vec::Vec<i32>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PortForwardResponse {
    #[prost(string, tag = "1")]
    pub url: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UpdateContainerResourcesRequest {
    #[prost(string, tag = "1")]
    pub container_id: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "2")]
    pub linux: ::core::option::Option<LinuxContainerResources>,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct UpdateContainerResourcesResponse {}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ReopenContainerLogRequest {
    #[prost(string, tag = "1")]
    pub container_id: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct ReopenContainerLogResponse {}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Image {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, repeated, tag = "2")]
    pub repo_tags: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(string, repeated, tag = "3")]
    pub repo_digests: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(uint64, tag = "4")]
    pub size: u64,
    #[prost(message, optional, tag = "5")]
    pub uid: ::core::option::Option<Int64Value>,
    #[prost(string, tag = "6")]
    pub username: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "7")]
    pub spec: ::core::option::Option<ImageSpec>,
    #[prost(bool, tag = "8")]
    pub pinned: bool,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListImagesRequest {
    #[prost(message, optional, tag = "1")]
    pub filter: ::core::option::Option<ImageFilter>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListImagesResponse {
    #[prost(message, repeated, tag = "1")]
    pub images: ::prost::alloc::vec::Vec<Image>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ImageFilter {
    #[prost(message, optional, tag = "1")]
    pub image: ::core::option::Option<ImageSpec>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ImageStatusRequest {
    #[prost(message, optional, tag = "1")]
    pub image: ::core::option::Option<ImageSpec>,
    #[prost(bool, tag = "2")]
    pub verbose: bool,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ImageStatusResponse {
    #[prost(message, optional, tag = "1")]
    pub image: ::core::option::Option<Image>,
    #[prost(map = "string, string", tag = "2")]
    pub info:
        ::std::collections::HashMap<::prost::alloc::string::String, ::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AuthConfig {
    #[prost(string, tag = "1")]
    pub username: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub password: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub auth: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub server_address: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub identity_token: ::prost::alloc::string::String,
    #[prost(string, tag = "6")]
    pub registry_token: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PullImageRequest {
    #[prost(message, optional, tag = "1")]
    pub image: ::core::option::Option<ImageSpec>,
    #[prost(message, optional, tag = "2")]
    pub auth: ::core::option::Option<AuthConfig>,
    #[prost(message, optional, tag = "3")]
    pub sandbox_config: ::core::option::Option<PodSandboxConfig>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PullImageResponse {
    #[prost(string, tag = "1")]
    pub image_ref: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RemoveImageRequest {
    #[prost(message, optional, tag = "1")]
    pub image: ::core::option::Option<ImageSpec>,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct RemoveImageResponse {}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct ImageFsInfoRequest {}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ImageFsInfoResponse {
    #[prost(message, repeated, tag = "1")]
    pub image_filesystems: ::prost::alloc::vec::Vec<FilesystemUsage>,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum PodSandboxState {
    SandboxReady = 0,
    SandboxNotready = 1,
}
impl PodSandboxState {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::SandboxReady => "SANDBOX_READY",
            Self::SandboxNotready => "SANDBOX_NOTREADY",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "SANDBOX_READY" => Some(Self::SandboxReady),
            "SANDBOX_NOTREADY" => Some(Self::SandboxNotready),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum NamespaceMode {
    Pod = 0,
    Container = 1,
    Node = 2,
    Target = 3,
}
impl NamespaceMode {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Pod => "POD",
            Self::Container => "CONTAINER",
            Self::Node => "NODE",
            Self::Target => "TARGET",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "POD" => Some(Self::Pod),
            "CONTAINER" => Some(Self::Container),
            "NODE" => Some(Self::Node),
            "TARGET" => Some(Self::Target),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum SecurityProfileType {
    RuntimeDefault = 0,
    Unconfined = 1,
    Localhost = 2,
}
impl SecurityProfileType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::RuntimeDefault => "RuntimeDefault",
            Self::Unconfined => "Unconfined",
            Self::Localhost => "Localhost",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "RuntimeDefault" => Some(Self::RuntimeDefault),
            "Unconfined" => Some(Self::Unconfined),
            "Localhost" => Some(Self::Localhost),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum Protocol {
    Tcp = 0,
    Udp = 1,
    Sctp = 2,
}
impl Protocol {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Tcp => "TCP",
            Self::Udp => "UDP",
            Self::Sctp => "SCTP",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "TCP" => Some(Self::Tcp),
            "UDP" => Some(Self::Udp),
            "SCTP" => Some(Self::Sctp),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum MountPropagation {
    PropagationPrivate = 0,
    PropagationHostToContainer = 1,
    PropagationBidirectional = 2,
}
impl MountPropagation {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::PropagationPrivate => "PROPAGATION_PRIVATE",
            Self::PropagationHostToContainer => "PROPAGATION_HOST_TO_CONTAINER",
            Self::PropagationBidirectional => "PROPAGATION_BIDIRECTIONAL",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "PROPAGATION_PRIVATE" => Some(Self::PropagationPrivate),
            "PROPAGATION_HOST_TO_CONTAINER" => Some(Self::PropagationHostToContainer),
            "PROPAGATION_BIDIRECTIONAL" => Some(Self::PropagationBidirectional),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum ContainerState {
    ContainerCreated = 0,
    ContainerRunning = 1,
    ContainerExited = 2,
    ContainerUnknown = 3,
}
impl ContainerState {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::ContainerCreated => "CONTAINER_CREATED",
            Self::ContainerRunning => "CONTAINER_RUNNING",
            Self::ContainerExited => "CONTAINER_EXITED",
            Self::ContainerUnknown => "CONTAINER_UNKNOWN",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "CONTAINER_CREATED" => Some(Self::ContainerCreated),
            "CONTAINER_RUNNING" => Some(Self::ContainerRunning),
            "CONTAINER_EXITED" => Some(Self::ContainerExited),
            "CONTAINER_UNKNOWN" => Some(Self::ContainerUnknown),
            _ => None,
        }
    }
}
/// Generated client implementations.
pub mod runtime_service_client {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value
    )]
    use tonic::codegen::http::Uri;
    use tonic::codegen::*;
    #[derive(Debug, Clone)]
    pub struct RuntimeServiceClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl RuntimeServiceClient<tonic::transport::Channel> {
        /// Attempt to create a new client by connecting to a given endpoint.
        pub async fn connect<D>(dst: D) -> Result<Self, tonic::transport::Error>
        where
            D: TryInto<tonic::transport::Endpoint>,
            D::Error: Into<StdError>,
        {
            let conn = tonic::transport::Endpoint::new(dst)?.connect().await?;
            Ok(Self::new(conn))
        }
    }
    impl<T> RuntimeServiceClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::BoxBody>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + std::marker::Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + std::marker::Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> RuntimeServiceClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                    http::Request<tonic::body::BoxBody>,
                    Response = http::Response<
                        <T as tonic::client::GrpcService<tonic::body::BoxBody>>::ResponseBody,
                    >,
                >,
            <T as tonic::codegen::Service<http::Request<tonic::body::BoxBody>>>::Error:
                Into<StdError> + std::marker::Send + std::marker::Sync,
        {
            RuntimeServiceClient::new(InterceptedService::new(inner, interceptor))
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        pub async fn version(
            &mut self,
            request: impl tonic::IntoRequest<super::VersionRequest>,
        ) -> std::result::Result<tonic::Response<super::VersionResponse>, tonic::Status> {
            self.inner.ready().await.map_err(|e| {
                tonic::Status::unknown(format!("Service was not ready: {}", e.into()))
            })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static("/runtime.v1.RuntimeService/Version");
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("runtime.v1.RuntimeService", "Version"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn run_pod_sandbox(
            &mut self,
            request: impl tonic::IntoRequest<super::RunPodSandboxRequest>,
        ) -> std::result::Result<tonic::Response<super::RunPodSandboxResponse>, tonic::Status>
        {
            self.inner.ready().await.map_err(|e| {
                tonic::Status::unknown(format!("Service was not ready: {}", e.into()))
            })?;
            let codec = tonic::codec::ProstCodec::default();
            let path =
                http::uri::PathAndQuery::from_static("/runtime.v1.RuntimeService/RunPodSandbox");
            let mut req = request.into_request();
            req.extensions_mut().insert(GrpcMethod::new(
                "runtime.v1.RuntimeService",
                "RunPodSandbox",
            ));
            self.inner.unary(req, path, codec).await
        }
        pub async fn stop_pod_sandbox(
            &mut self,
            request: impl tonic::IntoRequest<super::StopPodSandboxRequest>,
        ) -> std::result::Result<tonic::Response<super::StopPodSandboxResponse>, tonic::Status>
        {
            self.inner.ready().await.map_err(|e| {
                tonic::Status::unknown(format!("Service was not ready: {}", e.into()))
            })?;
            let codec = tonic::codec::ProstCodec::default();
            let path =
                http::uri::PathAndQuery::from_static("/runtime.v1.RuntimeService/StopPodSandbox");
            let mut req = request.into_request();
            req.extensions_mut().insert(GrpcMethod::new(
                "runtime.v1.RuntimeService",
                "StopPodSandbox",
            ));
            self.inner.unary(req, path, codec).await
        }
        pub async fn remove_pod_sandbox(
            &mut self,
            request: impl tonic::IntoRequest<super::RemovePodSandboxRequest>,
        ) -> std::result::Result<tonic::Response<super::RemovePodSandboxResponse>, tonic::Status>
        {
            self.inner.ready().await.map_err(|e| {
                tonic::Status::unknown(format!("Service was not ready: {}", e.into()))
            })?;
            let codec = tonic::codec::ProstCodec::default();
            let path =
                http::uri::PathAndQuery::from_static("/runtime.v1.RuntimeService/RemovePodSandbox");
            let mut req = request.into_request();
            req.extensions_mut().insert(GrpcMethod::new(
                "runtime.v1.RuntimeService",
                "RemovePodSandbox",
            ));
            self.inner.unary(req, path, codec).await
        }
        pub async fn pod_sandbox_status(
            &mut self,
            request: impl tonic::IntoRequest<super::PodSandboxStatusRequest>,
        ) -> std::result::Result<tonic::Response<super::PodSandboxStatusResponse>, tonic::Status>
        {
            self.inner.ready().await.map_err(|e| {
                tonic::Status::unknown(format!("Service was not ready: {}", e.into()))
            })?;
            let codec = tonic::codec::ProstCodec::default();
            let path =
                http::uri::PathAndQuery::from_static("/runtime.v1.RuntimeService/PodSandboxStatus");
            let mut req = request.into_request();
            req.extensions_mut().insert(GrpcMethod::new(
                "runtime.v1.RuntimeService",
                "PodSandboxStatus",
            ));
            self.inner.unary(req, path, codec).await
        }
        pub async fn list_pod_sandbox(
            &mut self,
            request: impl tonic::IntoRequest<super::ListPodSandboxRequest>,
        ) -> std::result::Result<tonic::Response<super::ListPodSandboxResponse>, tonic::Status>
        {
            self.inner.ready().await.map_err(|e| {
                tonic::Status::unknown(format!("Service was not ready: {}", e.into()))
            })?;
            let codec = tonic::codec::ProstCodec::default();
            let path =
                http::uri::PathAndQuery::from_static("/runtime.v1.RuntimeService/ListPodSandbox");
            let mut req = request.into_request();
            req.extensions_mut().insert(GrpcMethod::new(
                "runtime.v1.RuntimeService",
                "ListPodSandbox",
            ));
            self.inner.unary(req, path, codec).await
        }
        pub async fn create_container(
            &mut self,
            request: impl tonic::IntoRequest<super::CreateContainerRequest>,
        ) -> std::result::Result<tonic::Response<super::CreateContainerResponse>, tonic::Status>
        {
            self.inner.ready().await.map_err(|e| {
                tonic::Status::unknown(format!("Service was not ready: {}", e.into()))
            })?;
            let codec = tonic::codec::ProstCodec::default();
            let path =
                http::uri::PathAndQuery::from_static("/runtime.v1.RuntimeService/CreateContainer");
            let mut req = request.into_request();
            req.extensions_mut().insert(GrpcMethod::new(
                "runtime.v1.RuntimeService",
                "CreateContainer",
            ));
            self.inner.unary(req, path, codec).await
        }
        pub async fn start_container(
            &mut self,
            request: impl tonic::IntoRequest<super::StartContainerRequest>,
        ) -> std::result::Result<tonic::Response<super::StartContainerResponse>, tonic::Status>
        {
            self.inner.ready().await.map_err(|e| {
                tonic::Status::unknown(format!("Service was not ready: {}", e.into()))
            })?;
            let codec = tonic::codec::ProstCodec::default();
            let path =
                http::uri::PathAndQuery::from_static("/runtime.v1.RuntimeService/StartContainer");
            let mut req = request.into_request();
            req.extensions_mut().insert(GrpcMethod::new(
                "runtime.v1.RuntimeService",
                "StartContainer",
            ));
            self.inner.unary(req, path, codec).await
        }
        pub async fn stop_container(
            &mut self,
            request: impl tonic::IntoRequest<super::StopContainerRequest>,
        ) -> std::result::Result<tonic::Response<super::StopContainerResponse>, tonic::Status>
        {
            self.inner.ready().await.map_err(|e| {
                tonic::Status::unknown(format!("Service was not ready: {}", e.into()))
            })?;
            let codec = tonic::codec::ProstCodec::default();
            let path =
                http::uri::PathAndQuery::from_static("/runtime.v1.RuntimeService/StopContainer");
            let mut req = request.into_request();
            req.extensions_mut().insert(GrpcMethod::new(
                "runtime.v1.RuntimeService",
                "StopContainer",
            ));
            self.inner.unary(req, path, codec).await
        }
        pub async fn remove_container(
            &mut self,
            request: impl tonic::IntoRequest<super::RemoveContainerRequest>,
        ) -> std::result::Result<tonic::Response<super::RemoveContainerResponse>, tonic::Status>
        {
            self.inner.ready().await.map_err(|e| {
                tonic::Status::unknown(format!("Service was not ready: {}", e.into()))
            })?;
            let codec = tonic::codec::ProstCodec::default();
            let path =
                http::uri::PathAndQuery::from_static("/runtime.v1.RuntimeService/RemoveContainer");
            let mut req = request.into_request();
            req.extensions_mut().insert(GrpcMethod::new(
                "runtime.v1.RuntimeService",
                "RemoveContainer",
            ));
            self.inner.unary(req, path, codec).await
        }
        pub async fn list_containers(
            &mut self,
            request: impl tonic::IntoRequest<super::ListContainersRequest>,
        ) -> std::result::Result<tonic::Response<super::ListContainersResponse>, tonic::Status>
        {
            self.inner.ready().await.map_err(|e| {
                tonic::Status::unknown(format!("Service was not ready: {}", e.into()))
            })?;
            let codec = tonic::codec::ProstCodec::default();
            let path =
                http::uri::PathAndQuery::from_static("/runtime.v1.RuntimeService/ListContainers");
            let mut req = request.into_request();
            req.extensions_mut().insert(GrpcMethod::new(
                "runtime.v1.RuntimeService",
                "ListContainers",
            ));
            self.inner.unary(req, path, codec).await
        }
        pub async fn container_status(
            &mut self,
            request: impl tonic::IntoRequest<super::ContainerStatusRequest>,
        ) -> std::result::Result<tonic::Response<super::ContainerStatusResponse>, tonic::Status>
        {
            self.inner.ready().await.map_err(|e| {
                tonic::Status::unknown(format!("Service was not ready: {}", e.into()))
            })?;
            let codec = tonic::codec::ProstCodec::default();
            let path =
                http::uri::PathAndQuery::from_static("/runtime.v1.RuntimeService/ContainerStatus");
            let mut req = request.into_request();
            req.extensions_mut().insert(GrpcMethod::new(
                "runtime.v1.RuntimeService",
                "ContainerStatus",
            ));
            self.inner.unary(req, path, codec).await
        }
        pub async fn container_stats(
            &mut self,
            request: impl tonic::IntoRequest<super::ContainerStatsRequest>,
        ) -> std::result::Result<tonic::Response<super::ContainerStatsResponse>, tonic::Status>
        {
            self.inner.ready().await.map_err(|e| {
                tonic::Status::unknown(format!("Service was not ready: {}", e.into()))
            })?;
            let codec = tonic::codec::ProstCodec::default();
            let path =
                http::uri::PathAndQuery::from_static("/runtime.v1.RuntimeService/ContainerStats");
            let mut req = request.into_request();
            req.extensions_mut().insert(GrpcMethod::new(
                "runtime.v1.RuntimeService",
                "ContainerStats",
            ));
            self.inner.unary(req, path, codec).await
        }
        pub async fn exec_sync(
            &mut self,
            request: impl tonic::IntoRequest<super::ExecSyncRequest>,
        ) -> std::result::Result<tonic::Response<super::ExecSyncResponse>, tonic::Status> {
            self.inner.ready().await.map_err(|e| {
                tonic::Status::unknown(format!("Service was not ready: {}", e.into()))
            })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static("/runtime.v1.RuntimeService/ExecSync");
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("runtime.v1.RuntimeService", "ExecSync"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn exec(
            &mut self,
            request: impl tonic::IntoRequest<super::ExecRequest>,
        ) -> std::result::Result<tonic::Response<super::ExecResponse>, tonic::Status> {
            self.inner.ready().await.map_err(|e| {
                tonic::Status::unknown(format!("Service was not ready: {}", e.into()))
            })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static("/runtime.v1.RuntimeService/Exec");
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("runtime.v1.RuntimeService", "Exec"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn attach(
            &mut self,
            request: impl tonic::IntoRequest<super::AttachRequest>,
        ) -> std::result::Result<tonic::Response<super::AttachResponse>, tonic::Status> {
            self.inner.ready().await.map_err(|e| {
                tonic::Status::unknown(format!("Service was not ready: {}", e.into()))
            })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static("/runtime.v1.RuntimeService/Attach");
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("runtime.v1.RuntimeService", "Attach"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn port_forward(
            &mut self,
            request: impl tonic::IntoRequest<super::PortForwardRequest>,
        ) -> std::result::Result<tonic::Response<super::PortForwardResponse>, tonic::Status>
        {
            self.inner.ready().await.map_err(|e| {
                tonic::Status::unknown(format!("Service was not ready: {}", e.into()))
            })?;
            let codec = tonic::codec::ProstCodec::default();
            let path =
                http::uri::PathAndQuery::from_static("/runtime.v1.RuntimeService/PortForward");
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("runtime.v1.RuntimeService", "PortForward"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn update_container_resources(
            &mut self,
            request: impl tonic::IntoRequest<super::UpdateContainerResourcesRequest>,
        ) -> std::result::Result<
            tonic::Response<super::UpdateContainerResourcesResponse>,
            tonic::Status,
        > {
            self.inner.ready().await.map_err(|e| {
                tonic::Status::unknown(format!("Service was not ready: {}", e.into()))
            })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/runtime.v1.RuntimeService/UpdateContainerResources",
            );
            let mut req = request.into_request();
            req.extensions_mut().insert(GrpcMethod::new(
                "runtime.v1.RuntimeService",
                "UpdateContainerResources",
            ));
            self.inner.unary(req, path, codec).await
        }
        pub async fn reopen_container_log(
            &mut self,
            request: impl tonic::IntoRequest<super::ReopenContainerLogRequest>,
        ) -> std::result::Result<tonic::Response<super::ReopenContainerLogResponse>, tonic::Status>
        {
            self.inner.ready().await.map_err(|e| {
                tonic::Status::unknown(format!("Service was not ready: {}", e.into()))
            })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/runtime.v1.RuntimeService/ReopenContainerLog",
            );
            let mut req = request.into_request();
            req.extensions_mut().insert(GrpcMethod::new(
                "runtime.v1.RuntimeService",
                "ReopenContainerLog",
            ));
            self.inner.unary(req, path, codec).await
        }
    }
}
/// Generated client implementations.
pub mod image_service_client {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value
    )]
    use tonic::codegen::http::Uri;
    use tonic::codegen::*;
    #[derive(Debug, Clone)]
    pub struct ImageServiceClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl ImageServiceClient<tonic::transport::Channel> {
        /// Attempt to create a new client by connecting to a given endpoint.
        pub async fn connect<D>(dst: D) -> Result<Self, tonic::transport::Error>
        where
            D: TryInto<tonic::transport::Endpoint>,
            D::Error: Into<StdError>,
        {
            let conn = tonic::transport::Endpoint::new(dst)?.connect().await?;
            Ok(Self::new(conn))
        }
    }
    impl<T> ImageServiceClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::BoxBody>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + std::marker::Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + std::marker::Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> ImageServiceClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                    http::Request<tonic::body::BoxBody>,
                    Response = http::Response<
                        <T as tonic::client::GrpcService<tonic::body::BoxBody>>::ResponseBody,
                    >,
                >,
            <T as tonic::codegen::Service<http::Request<tonic::body::BoxBody>>>::Error:
                Into<StdError> + std::marker::Send + std::marker::Sync,
        {
            ImageServiceClient::new(InterceptedService::new(inner, interceptor))
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        pub async fn list_images(
            &mut self,
            request: impl tonic::IntoRequest<super::ListImagesRequest>,
        ) -> std::result::Result<tonic::Response<super::ListImagesResponse>, tonic::Status>
        {
            self.inner.ready().await.map_err(|e| {
                tonic::Status::unknown(format!("Service was not ready: {}", e.into()))
            })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static("/runtime.v1.ImageService/ListImages");
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("runtime.v1.ImageService", "ListImages"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn image_status(
            &mut self,
            request: impl tonic::IntoRequest<super::ImageStatusRequest>,
        ) -> std::result::Result<tonic::Response<super::ImageStatusResponse>, tonic::Status>
        {
            self.inner.ready().await.map_err(|e| {
                tonic::Status::unknown(format!("Service was not ready: {}", e.into()))
            })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static("/runtime.v1.ImageService/ImageStatus");
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("runtime.v1.ImageService", "ImageStatus"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn pull_image(
            &mut self,
            request: impl tonic::IntoRequest<super::PullImageRequest>,
        ) -> std::result::Result<tonic::Response<super::PullImageResponse>, tonic::Status> {
            self.inner.ready().await.map_err(|e| {
                tonic::Status::unknown(format!("Service was not ready: {}", e.into()))
            })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static("/runtime.v1.ImageService/PullImage");
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("runtime.v1.ImageService", "PullImage"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn remove_image(
            &mut self,
            request: impl tonic::IntoRequest<super::RemoveImageRequest>,
        ) -> std::result::Result<tonic::Response<super::RemoveImageResponse>, tonic::Status>
        {
            self.inner.ready().await.map_err(|e| {
                tonic::Status::unknown(format!("Service was not ready: {}", e.into()))
            })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static("/runtime.v1.ImageService/RemoveImage");
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("runtime.v1.ImageService", "RemoveImage"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn image_fs_info(
            &mut self,
            request: impl tonic::IntoRequest<super::ImageFsInfoRequest>,
        ) -> std::result::Result<tonic::Response<super::ImageFsInfoResponse>, tonic::Status>
        {
            self.inner.ready().await.map_err(|e| {
                tonic::Status::unknown(format!("Service was not ready: {}", e.into()))
            })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static("/runtime.v1.ImageService/ImageFsInfo");
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("runtime.v1.ImageService", "ImageFsInfo"));
            self.inner.unary(req, path, codec).await
        }
    }
}
